### ISSUE TITLE
http dispatcher error processing events without a correlation id

### ISSUE THREAD

**Issue by jldec** [projectriff/function-sidecar#54]
Found this when trying to run S1P demo using redis-writer with http.
In this case the upstream java vote-stream-processor is emitting events every 2s.
Those events don't have a correlation id.

The sidecar eventually panics with the following error 
```
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 2018/02/19 20:48:45 Wrapper received Message{{"_list":"demo:votes-windows","_time":1519073323372}, map[timestamp:[1519073325372]]}
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 2018/02/19 20:48:47 Wrapper received Message{{"_list":"demo:votes-log","_time":1519073325367}, map[timestamp:[1519073327367]]}
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 2018/02/19 20:48:47 Wrapper received Message{{"_list":"demo:votes-windows","_time":1519073325372}, map[timestamp:[1519073327373]]}
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 2018/02/19 20:48:47 Error invoking http://localhost:8080: Post http://localhost:8080: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 2018/02/19 20:48:47 Error calling synch dispatcher Post http://localhost:8080: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 2018/02/19 20:48:47 Wrapper about to forward <nil>
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 2018/02/19 20:48:47 <<< %!s(<nil>)
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: panic: runtime error: invalid memory address or nil pointer dereference
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x83ba6a]
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: goroutine 31 [running]:
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: github.com/projectriff/function-sidecar/vendor/github.com/projectriff/message-transport/pkg/transport/kafka.encodeMessage(0x0, 0x0, 0xc4204be240, 0xc4205da000, 0x100, 0x23, 0xc63120)
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 	/go/src/github.com/projectriff/function-sidecar/vendor/github.com/projectriff/message-transport/pkg/transport/kafka/wireformat.go:79 +0x3a
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: github.com/projectriff/function-sidecar/vendor/github.com/projectriff/message-transport/pkg/transport/kafka.toKafka(0x0, 0x0, 0xc420282fd0, 0xf, 0x0)
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 	/go/src/github.com/projectriff/function-sidecar/vendor/github.com/projectriff/message-transport/pkg/transport/kafka/wireformat.go:36 +0x39
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: github.com/projectriff/function-sidecar/vendor/github.com/projectriff/message-transport/pkg/transport/kafka.(*producer).Send(0xc420144960, 0x7ffc71886789, 0x5, 0x0, 0x0, 0x0, 0x0)
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 	/go/src/github.com/projectriff/function-sidecar/vendor/github.com/projectriff/message-transport/pkg/transport/kafka/producer.go:35 +0x39
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: github.com/projectriff/function-sidecar/pkg/carrier.Run.func2(0xc19400, 0xc420166540, 0x7ffc71886789, 0x5, 0xc19540, 0xc420144960)
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 	/go/src/github.com/projectriff/function-sidecar/pkg/carrier/carrier.go:48 +0x14b
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: created by github.com/projectriff/function-sidecar/pkg/carrier.Run
default/redis-writer-56fb49c4d9-qdbc2[sidecar]: 	/go/src/github.com/projectriff/function-sidecar/pkg/carrier/carrier.go:41 +0xbb
```

switching the redis-writer function to use grpc instead of http fixes the issue.

```
default/redis-writer-6ff59f6fcc-t6xzr[sidecar]: 2018/02/19 20:52:06 Sidecar for function 'redis-writer' (function-replicas->dummy) using grpc dispatcher starting
default/redis-writer-6ff59f6fcc-t6xzr[sidecar]: 2018/02/19 20:52:06 Rebalanced: &{Type:rebalance start Claimed:map[] Released:map[] Current:map[]}
default/redis-writer-6ff59f6fcc-t6xzr[sidecar]: 2018/02/19 20:52:06 Rebalanced: &{Type:rebalance OK Claimed:map[function-replicas:[0]] Released:map[] Current:map[function-replicas:[0]]}
default/redis-writer-6ff59f6fcc-t6xzr[main]: Node started in 117ms
default/redis-writer-6ff59f6fcc-t6xzr[main]: gRPC loaded in 97ms
default/redis-writer-6ff59f6fcc-t6xzr[main]: HTTP loaded in 68ms
default/redis-writer-6ff59f6fcc-t6xzr[main]: gRPC running on localhost:10382
default/redis-writer-6ff59f6fcc-t6xzr[main]: HTTP running on http://localhost:8080
default/redis-writer-6ff59f6fcc-t6xzr[main]: Function invoker started in 287ms
default/redis-writer-6ff59f6fcc-t6xzr[main]: RIFF 1: Result: <Buffer 7b 22 5f 6c 69 73 74 22 3a 22 64 65 6d 6f 3a 76 6f 74 65 73 2d 6c 6f 67 22 2c 22 5f 74 69 6d 65 22 3a 31 35 31 39 30 37 33 35 32 33 33 36 37 7d>
default/redis-writer-6ff59f6fcc-t6xzr[main]: RIFF 1: Result: <Buffer 7b 22 5f 6c 69 73 74 22 3a 22 64 65 6d 6f 3a 76 6f 74 65 73 2d 77 69 6e 64 6f 77 73 22 2c 22 5f 74 69 6d 65 22 3a 31 35 31 39 30 37 33 35 32 33 33 37 ... >
default/redis-writer-6ff59f6fcc-t6xzr[sidecar]: 2018/02/19 20:52:07 <<< Message{{"_list":"demo:votes-log","_time":1519073523367}, map[Content-Type:[text/plain]]}
default/redis-writer-6ff59f6fcc-t6xzr[sidecar]: 2018/02/19 20:52:07 <<< Message{{"_list":"demo:votes-windows","_time":1519073523373}, map[Content-Type:[text/plain]]}
default/redis-writer-6ff59f6fcc-t6xzr[main]: RIFF 1: Result: <Buffer 7b 22 5f 6c 69 73 74 22 3a 22 64 65 6d 6f 3a 76 6f 74 65 73 2d 6c 6f 67 22 2c 22 5f 74 69 6d 65 22 3a 31 35 31 39 30 37 33 35 32 35 33 36 37 7d>
default/redis-writer-6ff59f6fcc-t6xzr[sidecar]: 2018/02/19 20:52:07 <<< Message{{"_list":"demo:votes-log","_time":1519073525367}, map[Content-Type:[text/plain]]}
```

**Comment by glyn** [comment]
@jldec I'm pretty sure I've fixed this problem as the diagnostics are clear, but I don't know how to run the S1P demo, so I haven't verified the fix.
